version: "3.7"
services:
  geobuf-cli:
    restart: always
    container_name: geobuf-cli
    build:
      context: ./
      dockerfile: ./cli/Dockerfile
    env_file:
      - .env
    volumes:
      - ./cli:/cli
      - ${VOLUME_PATH}:/volume
