version: "3.7"
services:
  geobuf-cli:
    restart: always
    container_name: geobuf-cli
    build:
      context: ./
      dockerfile: ./cli/Dockerfile
    env_file:
      - .env
    volumes:
      - ./cli:/cli
      - ${VOLUME_PATH}:/volume
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 5000:80
    volumes:
      - ${VOLUME_PATH}:/data
